src/users/urls.py
from django.conf.urls import include, url

from users.views import UserDetailView, UserUpdateView


app_name = 'users'

urlpatterns = [
    url(r'^skillsets/', include('skillsets.urls'), name='skillsets'),
    url(r'^profile/edit/$',
        UserUpdateView.as_view(), name='edit'),
    url(r'^profile/$', UserDetailView.as_view(), name='detail'),
    url(r'^$', include('profiles.urls'), name='profiles'),
    # url(r'^$', UserListView.as_view(), name='list'),
]

src/users/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from rest_framework.authtoken.models import Token

from profiles.models import Profile


class UserManager(BaseUserManager):

    def create(self, username, email, password=None, *args, **kwargs):
        """
        Creates and saves a User with the given username, email, and password.
        """
        user = self.model(username=username, email=email, **kwargs)
        user.set_password(password)
        user.save()
        profile = Profile(
            user=user,
        )
        profile.save()
        return user

    def create_superuser(self, username, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create(
            username=username,
            email=email,
            password=password,
            is_staff=True
        )
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):

    class Meta:
        abstract = False
        db_table = 'users'
        app_label = 'users'
        verbose_name = _('user')
        verbose_name_plural = _('users')

    email = models.EmailField(
        _('email address'), null=False, unique=True,
        error_messages={
            'unique': _('A user with that email already exists.'),
        }
    )
    username = models.CharField(
        _('username'), max_length=30, unique=True, blank=True, null=True,
        error_messages={
            'unique': _('A user with that username already exists.'),
        }
    )
    is_staff = models.BooleanField(
        _('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.')
    )
    is_active = models.BooleanField(
        _('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.')
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    first_name = models.CharField(
        _('first name'), max_length=30, null=True, blank=True)
    last_name = models.CharField(
        _('last name'), max_length=50, null=True, blank=True)
    title = models.CharField(_('title'), max_length=280, blank=True)
    description = models.TextField(_('description'), blank=True)
    years_experience = models.IntegerField(
        _('years of experience'), blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def save(self, *args, **kwargs):
        self.full_clean()
        super(User, self).save(*args, **kwargs)

    def __str__(self):
        return self.username


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created and instance.is_staff:
        Token.objects.create(user=instance)

src/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

from .models import User


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'title',
                  'email', 'password1', 'password2')

    title = forms.CharField(label=_('Job Title'), required=False)
    email = forms.EmailField(label=_('E-mail'), max_length=75, required=True)

    def save(self, commit=True):
        data = dict(self.cleaned_data)
        data['password'] = data.pop('password1')
        password2 = data.pop('password2')
        if password2 != data['password']:
            raise forms.ValidationError(
                _('Password fields do not match.'),
                code='invalid')
        return User.objects.create(**data)


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'title', 'email')

    username = forms.CharField(label=_('Username'), required=True)
    title = forms.CharField(label=_('Job Title'), required=False)
    email = forms.EmailField(label=_('E-mail'), max_length=75, required=True)


class UserLimitedForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'title')

    username = forms.CharField(label=_('Username'), required=True)
    title = forms.CharField(label=_('Job Title'), required=False)


class UserChangePasswordForm(forms.Form):

    password1 = forms.CharField(
        widget=forms.PasswordInput, label=_('New Password'), required=True)
    password2 = forms.CharField(
        widget=forms.PasswordInput,
        label=_('Confirm New Password'), required=True)

    def __init__(self, user, *args, **kwargs):
        self.user = User.objects.get(username=user.username)
        super(UserChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    _('Password fields must match.'),
                    code='password_mismatch',
                )
        return self.cleaned_data

    def save(self):
        self.user.set_password(self.cleaned_data['password1'])
        self.user.save()

src/users/views.py
from django.contrib.auth import (
    authenticate, get_backends, login, logout, update_session_auth_hash
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import password_reset, password_reset_confirm
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.response import TemplateResponse
from django.views.generic import (
    CreateView, DetailView, FormView, RedirectView, UpdateView
)
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser

from tshape.utils import MultiSerializerViewSetMixin, LoggedInMixin
from users.forms import (
    UserCreateForm, UserForm, UserChangePasswordForm
)
from users.models import User
from users.serializers import UserSerializer, UserUpdateSerializer


class UserViewSet(MultiSerializerViewSetMixin, viewsets.ModelViewSet):

    """A simple ViewSet for viewing and editing users."""
    queryset = User.objects.all()
    serializer_class = UserSerializer
    serializer_action_classes = {
        'update': UserUpdateSerializer,
        'partial_update': UserUpdateSerializer,
        'destroy': UserUpdateSerializer
    }
    permission_classes = [IsAdminUser]


class LoginView(FormView):

    form_class = AuthenticationForm
    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            logout(request)
        return super(LoginView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user.is_active:
            login(self.request, user)
            return HttpResponseRedirect(self.get_success_url(user))
        return render(self.request, self.template_name, {'form': form})

    def get_success_url(self, user, *args, **kwargs):
        return reverse_lazy('users:detail', kwargs={'username': user.username})


class LogoutView(RedirectView):

    success_url = reverse_lazy('index')

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(self.success_url)


class SignupView(CreateView):

    form_class = UserCreateForm
    template_name = 'users/signup.html'

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        get_backends()
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url(user))

    def get_success_url(self, user, *args, **kwargs):
        return reverse_lazy('users:detail', kwargs={'username': user.username})


class UserUpdateView(LoggedInMixin, UpdateView):

    form_class = UserForm
    template_name = 'users/edit.html'

    def get_object(self, *args, **kwargs):
        username = self.kwargs.get('username')
        if (not self.request.user.is_authenticated() or
                self.request.user.username != username):
            raise PermissionDenied
        return get_object_or_404(User, username=username)

    def form_valid(self, form, *args, **kwargs):
        form.save()
        return super(UserUpdateView, self).form_valid(form, *args, **kwargs)

    def get_success_url(self, *args, **kwargs):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


# only allow account owner to see email address
class UserDetailView(DetailView):

    template_name = 'users/detail.html'

    def get_object(self, *args, **kwargs):
        username = self.kwargs.get('username')
        return get_object_or_404(User, username=username)

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        if (not self.request.user.is_authenticated() or
                self.request.user.username != context['user'].username):
            context['permissions'] = True
        return context


class UserPasswordViews:

    @login_required()
    def change_password(request, *args, **kwargs):
        if request.method == 'POST':
            form = UserChangePasswordForm(user=request.user, data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                return HttpResponseRedirect(reverse('users:detail', kwargs={
                    'username': request.user.username}))
        else:
            form = UserChangePasswordForm(user=request.user)
        context = {
            'form': form,
        }
        return TemplateResponse(
            request, 'passwords/change_password.html', context)

    def reset_password(request):
        template = 'passwords/reset_password_form.html'
        email_template = 'passwords/reset_password_email.html'
        subject_template = 'passwords/reset_password_subject.txt'
        redirect = reverse('passwords:reset_password_done')
        return password_reset(request,
                              is_admin_site=False,
                              template_name=template,
                              email_template_name=email_template,
                              subject_template_name=subject_template,
                              post_reset_redirect=redirect,
                              from_email='info@tshape.io',
                              current_app='TShape')

    def reset_password_done(request):
        return render(request, 'passwords/reset_password_done.html')

    def reset_confirm(request, username=None, token=None):
        template = 'passwords/reset_password_confirm.html'
        redirect = reverse('passwords:reset_confirm_done')
        return password_reset_confirm(request,
                                      template_name=template,
                                      username=username,
                                      token=token,
                                      post_reset_redirect=redirect)

    def reset_confirm_done(request):
        return render(request, 'passwords/reset_password_complete.html')

src/users/templates/users/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block page_class %}page-signup{% endblock %}
{% block section_class %}section-signup{% endblock %}

{% block content %}
    <div class="signup">
    <h2>User Information</h2>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% if user %}
        <p>
            Username: {{ user.username }}<br />
            {% if permissions %}
                Email: {{ user.email }}<br />
            {% endif %}
            First Name: {{ user.first_name }}<br />
            Last Name: {{ user.last_name }}<br />
            Title: {{ user.title }}<br />
        </p>
        <p><a href="{% url 'users:edit' user.username %}">Edit User Information</a></p>
    {% else %}
        <p>Error: User does not exist.</p>
    {% endif %}
    </div>

{% endblock %}

src/users/templates/users/edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% block page_class %}page-signup{% endblock %}
{% block section_class %}section-signup{% endblock %}

{% block content %}
    <div class="signup">
    <h2>Edit User Information</h2>
    {% if form.errors %}
        {% for error in field.errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <form action="{% url 'users:edit' user.username %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
    <a href="{% url 'passwords:change_password' %}">Change Password</a>
    </div>

{% endblock %}

src/users/templates/users/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block page_class %}page-signup{% endblock %}
{% block section_class %}section-signup{% endblock %}

{% block content %}
    <div class="signup">
    <h2>Login</h2>
    {% if form.errors %}
        {% for error in field.errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.email.label_tag }}</td>
                <td>{{ form.email }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" class="button button--signup medium" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
    </div>

{% endblock %}

src/users/templates/users/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block page_class %}page-signup{% endblock %}
{% block section_class %}section-signup{% endblock %}

{% block content %}
    <div class="signup">
    <h2>Signup</h2>
    {% if form.errors %}
        {% for error in field.errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <form action='' method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Sign Up" class="button button--signup medium">
    </form>
    </div>

{% endblock %}